python main_finetune.py \
    --batch_size 64 \
    --epochs 200 \
    --accum_iter 1 \
    --input_size 224 \
    --drop_path 0.1 \
    --clip_grad 1.0 \
    --weight_decay 0.05 \
    --random_label_ratio 0.0 \
    --output_dir ./mbzuai_results/pretrain/tiny_imagenet_pretrain_gpt2_medium_classifier_correct_labels \
    --log_dir ./results/log_dir \
    --data_path /root/autodl-tmp/data/tiny-imagenet-200 \
    --nb_classes 200 \
    --dataset tiny-imagenet \
    --dist_eval \
